import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { SessionProvider as Provider } from "next-auth/react"
 import CustomSessionProvider from "@/components/SessionProviders";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   const session=await auth() 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomSessionProvider session={session}>
          <div className="min-h-screen bg-gray-50">
          <Navbar/>
          <main className=" container mx-auto px-4 py-8">
             {children}
          </main>
          <Toaster />
        </div>
        </CustomSessionProvider>
        
       
      </body>
    </html>
  );
}
